title: Threat level Midnight
author: Shubham Kishore
email: shubhkishore@github.com
description: > # this means to ignore newlines until "baseurl:"
  The pandemic reaches a new level of boring everyday. Thank god we have The Office.

# social links
twitter_username: shubh_kishore # DO NOT include the @ character, or else the build will fail!
github_username:  shubhkishore # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
